-- Wklej cały plik w Supabase > SQL Editor > New query > Run
create extension if not exists pgcrypto;
create table if not exists public.profiles (id uuid primary key references auth.users(id) on delete cascade, full_name text not null default 'Użytkownik', role text not null default 'user' check(role in ('admin','user')), created_at timestamptz not null default now());
create table if not exists public.shifts (id uuid primary key default gen_random_uuid(), title text not null check(length(title)<=100), details text check(length(details)<=500), start_at timestamptz not null, end_at timestamptz, created_by uuid not null references public.profiles(id), created_at timestamptz not null default now(), updated_at timestamptz not null default now(), check(end_at is null or end_at>start_at));
create table if not exists public.bookings (id uuid primary key default gen_random_uuid(), title text not null check(length(title)<=100), details text check(length(details)<=500), start_at timestamptz not null, end_at timestamptz, created_by uuid not null references public.profiles(id), created_at timestamptz not null default now(), updated_at timestamptz not null default now(), check(end_at is null or end_at>start_at));
create table if not exists public.shopping (id uuid primary key default gen_random_uuid(), title text not null check(length(title)<=100), details text check(length(details)<=500), quantity text check(length(quantity)<=30), is_done boolean not null default false, created_by uuid not null references public.profiles(id), created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create or replace function public.new_user_profile() returns trigger language plpgsql security definer set search_path=public as $$ begin insert into public.profiles(id,full_name) values(new.id,coalesce(new.raw_user_meta_data->>'full_name',split_part(new.email,'@',1))) on conflict do nothing; return new; end $$;
drop trigger if exists on_auth_user_created on auth.users;create trigger on_auth_user_created after insert on auth.users for each row execute procedure public.new_user_profile();
create or replace function public.is_admin() returns boolean language sql stable security definer set search_path=public as $$ select exists(select 1 from public.profiles where id=auth.uid() and role='admin') $$;
alter table public.profiles enable row level security;alter table public.shifts enable row level security;alter table public.bookings enable row level security;alter table public.shopping enable row level security;
revoke all on public.profiles,public.shifts,public.bookings,public.shopping from anon;grant select on public.profiles to authenticated;grant select,insert,update,delete on public.shifts,public.bookings,public.shopping to authenticated;
create policy "profiles read authenticated" on public.profiles for select to authenticated using(true);
create policy "shifts read" on public.shifts for select to authenticated using(true);create policy "shifts insert own" on public.shifts for insert to authenticated with check(created_by=auth.uid());create policy "shifts update owner admin" on public.shifts for update to authenticated using(created_by=auth.uid() or public.is_admin()) with check(created_by=auth.uid() or public.is_admin());create policy "shifts delete owner admin" on public.shifts for delete to authenticated using(created_by=auth.uid() or public.is_admin());
create policy "bookings read" on public.bookings for select to authenticated using(true);create policy "bookings insert own" on public.bookings for insert to authenticated with check(created_by=auth.uid());create policy "bookings update owner admin" on public.bookings for update to authenticated using(created_by=auth.uid() or public.is_admin()) with check(created_by=auth.uid() or public.is_admin());create policy "bookings delete owner admin" on public.bookings for delete to authenticated using(created_by=auth.uid() or public.is_admin());
create policy "shopping read" on public.shopping for select to authenticated using(true);create policy "shopping insert own" on public.shopping for insert to authenticated with check(created_by=auth.uid());create policy "shopping update" on public.shopping for update to authenticated using(true) with check(true);create policy "shopping delete owner admin" on public.shopping for delete to authenticated using(created_by=auth.uid() or public.is_admin());
-- Po utworzeniu pierwszego konta ustaw administratora:
-- update public.profiles set role='admin', full_name='Kuba' where id=(select id from auth.users where email='TU_WPISZ_EMAIL_ADMINA');
